services:
  mini-app:
    build:
      context: miniapp
      dockerfile: Dockerfile
    container_name: mini-app
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - ./nginx/certs/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
      - ./nginx/certs/cloudflare.crt:/etc/nginx/ssl/cloudflare.crt:ro
    environment:
      SERVER_NAME: ${SERVER_NAME}
