FROM golang:1.24-alpine
RUN go install github.com/air-verse/air@latest
RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
RUN apk add --no-cache tor bash postgresql-client
WORKDIR /app
CMD ["air"]