// Code generated by sqlgen. DO NOT EDIT.

package db

import (
    "context"

    "github.com/jackc/pgx/v5"
    "github.com/jackc/pgx/v5/pgconn"
    "github.com/valkey-io/valkey-go"
)

var batchMaxSize = 1000

type DBTX interface {
    Begin(context.Context) (pgx.Tx, error)
	Exec(context.Context, string, ...interface{}) (pgconn.CommandTag, error)
	Query(context.Context, string, ...interface{}) (pgx.Rows, error)
	QueryRow(context.Context, string, ...interface{}) pgx.Row
}

type DB struct {
{{- range .Queries }}
    {{ . | ToPascalCase }}Store *{{ . | ToPascalCase }}Store
{{- end }}
}

func new(db DBTX, redis valkey.Client) *DB {
    return &DB{
        {{- range .Queries }}
        {{ . | ToPascalCase }}Store: &{{ . | ToPascalCase }}Store{db: db, redis: redis, cx: context.Background()},
        {{- end }}
    }
}