// Code generated by sqlgen. DO NOT EDIT.

package models

import "database/sql/driver"
{{ range .Enums -}}
{{ $name := .Name | ToPascalCase }}
type {{ $name }} string

const (
    {{- range .Vals }}
    {{ $name }}{{ . | ToPascalCase }} = "{{ . }}"
    {{- end }}
)

func (e *{{ $name }}) Scan(value interface{}) error {
    if value == nil {
        *e = ""
        return nil
    }
    switch s := value.(type) {
	case []byte:
		*e = LinkStatusEnum(s)
	case string:
		*e = LinkStatusEnum(s)
	}
    return nil
}

func (ns {{ $name }}) Value() (driver.Value, error) {
	if ns == "" {
		return nil, nil
	}
	return string(ns), nil
}

func (e {{ $name }}) IsNull() bool {
    return e == ""
}
{{- end }}